[build]
  command = "npm run build --workspace packages/web"
  publish = "packages/web/dist"
  functions = "netlify/functions"

[build.environment]
  TMDB_API_KEY = "d52274bb19dbdd5dd305c09a7afcf1ef"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
